libreria/inventario/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.index, name='index'),
    path('autores', views.autores, name='autores'),
    path('autores/cambiarEstado/<int:id_autor>', views.cambiarEstadoAutor, name='cambiarEstadoAutor'),
    path('autores/registro', views.registroAutores, name='registroAutores'),
    path('autores/detalle/<int:id_autor>', views.detalleAutor, name='detalleAutor'),
    path('autores/editar/<int:id_autor>', views.editarAutor, name='editarAutor'),
    path('generos', views.generos, name='generos'),
    path('generos/registro', views.registroGeneros, name='registroGeneros'),
    path('generos/detalle/<int:id_genero>', views.detalleGenero, name='detalleGenero'),
    path('generos/editar/<int:id_genero>', views.editarGenero, name='editarGenero'),
    path('generos/cambiarEstado/<int:id_genero>', views.cambiarEstadoGenero, name='cambiarEstadoGenero'),
    path('movimientos', views.movimientos, name='movimientos'),
    path('movimientos/registro', views.registroMovimientos, name='registroMovimientos'),
    path('movimientos/detalle/<int:id_movimiento>', views.detalleMovimiento, name='detalleMovimiento'),
    path('movimientos/editar/<int:id_movimiento>', views.editarMovimiento, name='editarMovimiento'),
    path('movimientos/editar/estado/<int:id_movimiento>', views.editarEstadoMovimiento, name='editarEstadoMovimiento'),
    path('movimientos/agregar/<int:id_movimiento>', views.agregarPublicacionMovimiento, name='agregarPublicacionMovimiento'),
    path('movimientos/informe', views.informeMovimiento, name='informeMovimiento'),
    path('productos', views.productos, name='productos'),
    path('productos/cambiarEstado/<int:id_publicacion>', views.cambiarEstadoPublicacion, name='cambiarEstadoPublicacion'),
    path('productos/registro', views.registroProductos, name='registroProductos'),
    path('productos/detalle/<int:id_publicacion>', views.detallePublicacion, name='detallePublicacion'),
    path('productos/editar/<int:id_publicacion>', views.editarPublicacion, name='editarPublicacion'),
    path('editoriales', views.editoriales, name='editoriales'),
    path('editoriales/cambiarEstado/<int:id_editorial>', views.cambiarEstadoEditorial, name='cambiarEstadoEditorial'),
    path('editoriales/registro', views.registroEditoriales, name='registroEditoriales'),
    path('editoriales/detalle/<int:id_editorial>', views.detalleEditorial, name='detalleEditorial'),
    path('editoriales/editar/<int:id_editorial>', views.editarEditorial, name='editarEditorial'),
    path('personas', views.listaPersonas, name='listaPersonas'),
    path('personas/cambiarEstado/<int:id_persona>', views.cambiarEstadoPersona, name='cambiarEstadoPersona'),
    path('personas/registro', views.registroPersonas, name='registroPersonas'),
    path('personas/detalle/<int:id_persona>', views.detallePersonas, name='detallePersonas'),
    path('personas/editar/<int:id_persona>', views.editarPersonas, name='editarPersonas'),
    path('seed', views.seed, name='seed'),
    path('personas/editar/<int:id_persona>', views.editarPersonas, name='editarPersonas'),
    path('login', views.loginPerfil, name='login'),
    path('logout', views.logoutPerfil, name='logout'),
    path('accesoDenegado', views.accesoDenegado, name='accesoDenegado'),
    path('perfiles', views.perfiles, name='perfiles'),
    path('perfiles/registro', views.registroPerfil, name='registroPerfil'),
    path('perfiles/preregistro', views.preregistroPerfil, name='preregistroPerfil'),
    path('perfiles/<int:perfil_id>', views.detallePerfiles, name='detallePerfiles'),
    path('perfiles/editar/<int:id_perfil>', views.editarPerfil, name='editarPerfil'),
    path('perfiles/cambiarEstado/<int:id_perfil>', views.cambiarEstadoPerfil, name='cambiarEstadoPerfil'),
    # URLS Bruno Pozo
    path('compras/registro',views.registroCompras,name='registroCompras'),
    path('compras',views.listaCompras, name='compras'),
    path('compras/detalle/<int:id_compra>', views.detalleCompras, name='detalleCompras'),
    path('compras/editar/<int:id_compra>', views.editarCompras, name='editarCompras'),
    path('compras/editar/estado/<int:id_compra>', views.editarEstadoCompra, name='editarEstadoCompra'),
    path('bodegas', views.bodegas, name='bodegas'),
    path('bodegas/cambiarEstado/<int:id_bodega>', views.cambiarEstadoBodega, name='cambiarEstadoBodega'),
    path('bodegas/detalle/<int:id_bodega>', views.detalleBodegas, name='detalleBodegas'),
    path('bodegas/registro', views.registroBodegas, name='registroBodegas'),
    path('bodegas/editar/<int:id_bodega>',views.editarBodegas, name='editarBodegas'),
    path('compras/detalle/<int:id_compra>',views.detalleCompras,name='detalleCompras'),
    path('compras/editar/<int:id_compra>',views.editarCompras,name='editarCompras'),
    # path('compras/detalles',views.detalleCompras,)
    # URLS Pablo Cea
    path('proveedores/historial', views.proveedores, name='proveedores'),
    path('proveedores/registro', views.registroProveedores, name='registroProveedores'),
    path('proveedores/cambiarEstado/<int:id_proveedor>', views.cambiarEstadoProveedor, name='cambiarEstadoProveedor'),
    path('proveedores/detalle/<int:id_proveedor>', views.detalleProveedores, name='detalleProveedores'),
    path('proveedores/editar/<int:id_proveedor>',views.editarProveedor, name='editarProveedor'),
    path('pedidos/detalle/<int:id_pedido>', views.detallePedidos, name='detallePedidos'),
    path('pedidos/registro', views.registroPedidos, name='registroPedidos'),
    path('pedidos',views.pedidos, name='pedidos'),
    path('pedidos/editar/<int:id_pedido>', views.editarPedidos, name='editarPedidos'),
    path('pedidos/editar/estado/<int:id_pedido>', views.editarEstadoPedido, name='editarEstadoPedido'),
]

libreria/libreria/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

import inventario.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(inventario.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

libreria/inventario/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
import datetime

# Create your models here.
class Autor(models.Model):
    id_autor = models.AutoField(primary_key=True)
    nombres_autor = models.CharField(max_length=150, null = True)
    apellidos_autor = models.CharField(max_length=150, null = True)
    correo_autor = models.CharField(max_length=150, null = True)
    nacionalidad_autor = models.CharField(max_length=150, null = True)
    pseudonimo_autor = models.CharField(max_length=150)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return u'%s' % (self.pseudonimo_autor)

    class Meta:
        db_table = "autor"
        verbose_name_plural = "autores"
        managed = False

class Genero(models.Model):
    id_genero = models.AutoField(primary_key=True)
    nombre_genero = models.CharField(max_length=150)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return u'%s' % (self.nombre_genero)

    class Meta:
        db_table = "genero"
        verbose_name_plural = "generos"
        managed = False

class Editorial(models.Model):
    id_editorial = models.AutoField(primary_key=True)
    nombre_editorial = models.CharField(max_length=150)
    correo_editorial = models.CharField(max_length=150, null=True)
    telefono_editorial = models.CharField(max_length=150, null=True)
    direccion_editorial = models.CharField(max_length=150, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return u'%s' % (self.nombre_editorial)

    class Meta:
        db_table = "editorial"
        verbose_name_plural = "editoriales"
        managed = False

class Publicacion(models.Model):
    id_publicacion = models.AutoField(primary_key=True)
    id_editorial = models.ForeignKey(Editorial, on_delete=models.CASCADE, db_column='id_editorial')
    nombre = models.CharField(max_length=150)
    resumen = models.TextField()
    tipo_producto = models.CharField(max_length=150)
    edicion = models.CharField(max_length=150)
    fecha_publicacion = models.CharField(max_length=150)
    isbn = models.CharField(max_length=150)
    numero_serie = models.IntegerField()
    precio = models.IntegerField()
    autores = models.ManyToManyField(Autor, through='Autor_Publicacion')
    generos = models.ManyToManyField(Genero, through='Genero_Publicacion')
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return u'%s' % (self.nombre)

    def fecha_publicacion_ddmmaa(self):
        fecha = datetime.datetime.strptime(self.fecha_publicacion, '%Y-%m-%d %H:%M:%S.%f')
        fecha_formateada = fecha.strftime("%m/%d/%Y")
        return fecha_formateada

    def fecha_publicacion_normal(self):
        fecha = datetime.datetime.strptime(self.fecha_publicacion, '%Y-%m-%d %H:%M:%S.%f')
        fecha_formateada = fecha.strftime("%m/%d/%Y")
        return fecha

    class Meta:
        db_table = "publicacion"
        verbose_name_plural = "publicaciones"
        managed = False

class Genero_Publicacion(models.Model):
    id_genero = models.ForeignKey(Genero, on_delete=models.CASCADE, db_column='id_genero')
    id_publicacion = models.ForeignKey(Publicacion, on_delete=models.CASCADE, db_column='id_publicacion')

    # def __str__(self):
    #     return u'%s' % (self.id_publicacion.nombre + " escrito por" + self.id_genero.pseudonimo_genero)

    class Meta:
        db_table = "genero_publicacion"
        verbose_name_plural = "genero_publicaciones"
        managed = False

class Autor_Publicacion(models.Model):
    id_autor = models.ForeignKey(Autor, on_delete=models.CASCADE, db_column='id_autor')
    id_publicacion = models.ForeignKey(Publicacion, on_delete=models.CASCADE, db_column='id_publicacion')

    # def __str__(self):
    #     return u'%s' % (self.id_publicacion.nombre + " escrito por" + self.id_autor.pseudonimo_autor)

    class Meta:
        db_table = "autor_publicacion"
        verbose_name_plural = "autor_publicaciones"
        managed = False

class Bodega(models.Model):
    id_bodega = models.AutoField(primary_key=True)
    nombre_bodega = models.CharField(max_length=150)
    direccion = models.CharField(max_length=150)
    comuna = models.CharField(max_length=150)
    telefono_bodega = models.CharField(max_length=150)
    publicaciones = models.ManyToManyField(Publicacion, through='Publicacion_Bodega')
    is_active = models.BooleanField(default=True)
    
    def __str__(self):
        return u'%s' % (self.nombre_bodega)

    class Meta:
        db_table = "bodega"
        verbose_name_plural = "bodegas"
        managed = False

class Publicacion_Bodega(models.Model):
    id_bodega = models.ForeignKey(Bodega, on_delete=models.CASCADE, db_column='id_bodega')
    id_publicacion = models.ForeignKey(Publicacion, on_delete=models.CASCADE, db_column='id_publicacion')
    cantidad = models.IntegerField(null=True)
    
    # def __str__(self):
    #     return u'%s' % (self.id_publicacion.nombre + " escrito por" + self.id_autor.pseudonimo_autor)

    class Meta:
        db_table = "publicacion_bodega"
        verbose_name_plural = "publicacion_bodegas"
        managed = False

class Persona(models.Model):
    id_persona = models.AutoField(primary_key=True)
    nombres = models.CharField(max_length=150)
    apellidos = models.CharField(max_length=150, null=True)
    rut = models.CharField(max_length=150)
    direccion = models.CharField(max_length=150, null=True)
    correo = models.CharField(max_length=150, null=True)
    telefono = models.CharField(max_length=150, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return u'%s' % (self.nombres)

    class Meta:
        db_table = "persona"
        verbose_name_plural = "personas"
        managed = False

class Perfil(AbstractUser):
    id = models.AutoField(primary_key=True)
    id_persona = models.ForeignKey(Persona, on_delete=models.CASCADE, db_column='id_persona')
    id_bodega = models.ForeignKey(Bodega, on_delete=models.CASCADE, db_column='id_bodega')
    username = models.CharField(max_length=150, unique=True)
    tipo_usuario = models.CharField(max_length=150)
    
    def __str__(self):
        return u'%s' % (self.username)

    USERNAME_FIELD = 'username'
    
    class Meta:
        db_table = "perfil"
        verbose_name_plural = "perfiles"
        managed = False


class Proveedor(models.Model):
    id_proveedor = models.AutoField(primary_key=True)
    nombre_proveedor = models.CharField(max_length=150, null=True)
    direccion_proveedor = models.CharField(max_length=150, null=True)
    comuna_proveedor = models.CharField(max_length=150, null=True)
    correo_proveedor = models.CharField(max_length=150, null=True)
    telefono_proveedor = models.CharField(max_length=150, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return u'%s' % (self.nombre_proveedor)

    class Meta:
        db_table = "proveedor"
        verbose_name_plural = "proveedores"
        managed = False

class Pedido(models.Model):
    id_pedido = models.AutoField(primary_key=True)
    id = models.ForeignKey(Perfil, on_delete=models.CASCADE, db_column='id')
    id_bodega = models.ForeignKey(Bodega, on_delete=models.CASCADE, db_column='id_bodega')
    id_proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE, db_column='id_proveedor')
    fecha_pedido = models.CharField(max_length=150)
    total_pedido = models.CharField(max_length=150)
    publicaciones = models.ManyToManyField(Publicacion, through='Publicacion_Pedido')
    estado = models.CharField(max_length=150)

    def fecha_pedido_normal(self):
        fecha = datetime.datetime.strptime(self.fecha_pedido, '%Y-%m-%d %H:%M:%S.%f')
        return fecha

    def fecha_pedido_ddmmaa(self):
        fecha = datetime.datetime.strptime(self.fecha_pedido, '%Y-%m-%d %H:%M:%S.%f')
        fecha_formateada = fecha.strftime("%m/%d/%Y")
        return fecha_formateada
    
    class Meta:
        db_table = "pedido"
        verbose_name_plural = "pedidos"
        managed = False

class Publicacion_Pedido(models.Model):
    id_publicacion = models.ForeignKey(Publicacion, on_delete=models.CASCADE, db_column='id_publicacion')
    id_pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE, db_column='id_pedido')
    cantidad = models.IntegerField(null=True)
    precio_proveedor = models.IntegerField(null=True)

    # def __str__(self):
    #     return u'%s' % (self.nombre_genero)
    
    class Meta:
        db_table = "publicacion_pedido"
        verbose_name_plural = "publicacion_pedidos"
        managed = False

class Compra(models.Model):
    id_compra = models.AutoField(primary_key=True)
    id_bodega = models.ForeignKey(Bodega, on_delete=models.CASCADE, db_column='id_bodega')
    id_persona = models.ForeignKey(Persona, on_delete=models.CASCADE, db_column='id_persona')
    total = models.IntegerField(null=True)
    metodo_pago = models.CharField(max_length=150)
    fecha_compra = models.CharField(max_length=150)
    publicaciones = models.ManyToManyField(Publicacion, through='Publicacion_Compra')
    estado = models.CharField(max_length=150)
    
    def fecha_compra_ddmmaa(self):
        fecha = datetime.datetime.strptime(self.fecha_compra, '%Y-%m-%d %H:%M:%S.%f')
        fecha_formateada = fecha.strftime("%m/%d/%Y")
        return fecha_formateada
    
    def fecha_compra_normal(self):
        fecha = datetime.datetime.strptime(self.fecha_compra, '%Y-%m-%d %H:%M:%S.%f')
        return fecha

    class Meta:
        db_table = "compra"
        verbose_name_plural = "compras"
        managed = False

class Publicacion_Compra(models.Model):
    id_publicacion = models.ForeignKey(Publicacion, on_delete=models.CASCADE, db_column='id_publicacion')
    id_compra = models.ForeignKey(Compra, on_delete=models.CASCADE, db_column='id_compra')
    cantidad = models.IntegerField(null=True)

libreria/inventario/templates/proveedores/detalle.html
{% extends 'layout.html' %}

{% block contenido %}
<div class="container">
    <div class="card mb-4">
        <div class="card-header text-center">
            <h3>
                Detalle Proveedor
            </h3>
        </div>
        <div class="card-body">
            <div class="row">
                <h3>Proveedor</h3>
                <hr>
                <label for="nombre" class="col-4 col-md-2 col-form-label text-end">Nombre:</label>
                <div class="col-8 col-md-4">
                    <input type="text" readonly="" class="form-control-plaintext" id="nombre" value="{{proveedor.nombre_proveedor}}">
                </div>
                <label for="apellido" class="col-4 col-md-2 col-form-label text-end">Dirección:</label>
                <div class="col-8 col-md-4">
                    <input type="text" readonly="" class="form-control-plaintext" id="direccion" value="{{proveedor.direccion_proveedor}}">
                </div>
                <label for="correo" class="col-4 col-md-2 col-form-label text-end">Correo:</label>
                <div class="col-8 col-md-4">
                    <input type="text" readonly="" class="form-control-plaintext" id="correo" value="{{proveedor.correo_proveedor}}">
                </div>
                <label for="nacionalidad" class="col-4 col-md-2 col-form-label text-end">Comuna:</label>
                <div class="col-8 col-md-4">
                    <input type="text" readonly="" class="form-control-plaintext" id="comuna" value="{{proveedor.comuna_proveedor}}">
                </div>
                <label for="pseudonimo" class="col-4 col-md-2 col-form-label text-end">Teléfono:</label>
                <div class="col-8 col-md-4">
                    <input type="text" readonly="" class="form-control-plaintext" id="telefono" value="{{proveedor.telefono_proveedor}}">
                </div>
                <label for="Estaod" class="col-4 col-md-2 col-form-label text-end">Estado:</label>
                <div class="col-8 col-md-4">
                    {% if proveedor.is_active == False %}
                    <span class="badge bg-danger">Inactivo</span>
                    {% else %}
                        <span class="badge bg-success">Activo</span>
                    {% endif %}</p>
                </div>
            </div>
        </div>
        <div class="card-footer text-end">
            <a href="{% url 'editarProveedor' proveedor.id_proveedor %}">
                <button class="btn btn-warning text">
                    Editar
                </button>
            </a>
        </div>
    </div>
    <div class="card mb-4">
        <div class="card-header text-center">
            <h3>
                Pedidos
            </h3>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Bodega</th>
                            <th>Fecha</th>
                            <th>Total</th>
                            <th>Acción</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for pedido in proveedor.pedido_set.all %}
                        <tr>
                            <td>{{pedido.id_pedido}}</td>
                            <td>{{pedido.id_bodega}}</td>
                            <td>
                                {{pedido.fecha_pedido}}
                            </td>
                            <td>{{pedido.total_pedido}}</td>
                            <td>
                                
                                <a href="">
                                    <button class="btn btn-primary">ver</button>
                                </a>
                                
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
   
{% endblock contenido %}

libreria/inventario/templates/proveedores/editar.html
{% extends 'layout.html' %}
{% block contenido %}
<div class= "container p-3">
  <div class="card">
    <div class="card-header">
      {{titulo}}
    </div>
    <div class="card-body">
      <form action="{% url 'editarProveedor' proveedor.id_proveedor %}" method = "POST">
          {% csrf_token %}
          <div class="mb-3">
              <label class="form-label">Nombre</label>
              <input type="text" class="form-control" id="nombreP" name="nombreP" value="{{proveedor.nombre_proveedor}}">
            </div>
          <div class="mb-3">
            <label class="form-label">Dirección</label>
            <input type="text" class="form-control" id="direccionP" name="direccionP" value="{{proveedor.direccion_proveedor}}">
          </div>
          <div class="mb-3">
            <label class="form-label">Comuna</label>
            <input type="text" class="form-control" id="comunaP" name="comunaP" value="{{proveedor.comuna_proveedor}}">
          </div>
          <div class="mb-3">
              <label class="form-label">Correo</label>
              <input type="email" class="form-control" id="correoP" name="correoP" value="{{proveedor.correo_proveedor}}">
          </div>
          <div class="mb-3">
              <label class="form-label">Teléfono</label>
              <input type="text" class="form-control" id="telefonoP" name="telefonoP" value="{{proveedor.telefono_proveedor}}">
          </div>
          <div class="form-check mb-3">
            <input class="form-check-input" type="checkbox" id="activo" name="activo" {% if proveedor.is_active %}checked{% endif %}>
            <label class="form-check-label" for="activo">
              Activo
            </label>
        </div>
          <br>
          <button type="submit" class="btn btn-primary">Editar</button>
        </form>

    </div>
  </div>
</div>

{% if toast %}
        <div class="toast-container text-bg-primary position-fixed bottom-0 start-0 p-3">
            {% if toast == "Error" %}
                <div id="liveToast" class="toast bg-danger text-light" role="alert" aria-live="assertive" aria-atomic="true">
            {% else %}
                <div id="liveToast" class="toast bg-success text-light" role="alert" aria-live="assertive" aria-atomic="true">
            {% endif %}
                <div class="toast-header">
                    <i class="fa-solid fa-circle-exclamation m-1"></i>
                    <strong class="me-auto">{{toast}}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
                <div class="toast-body">
                    {{mensaje}}
                </div>
            </div>
        </div>
        <script> 
            const toastLiveExample = document.getElementById('liveToast')
            const toast = new bootstrap.Toast(toastLiveExample)
            toast.show()
        </script>
        {% endif %}
{% endblock contenido %}

libreria/inventario/templates/proveedores/historial.html
{% extends 'layout.html' %}

{% block contenido %}
<div class="container">
    <div class="card">
        <div class="card-header">
            {{titulo}}
        </div>
        <div class="card-body">
            <table class="table text-center">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Direccion</th>
                        <th>Comuna</th>
                        <th>Correo</th>
                        <th>Teléfono</th>
                        <th>Estado</th>
                        <th>Accion</th>
                    </tr>
                </thead>
                <tbody>
                    {% for proveedor in proveedores %}
                    <tr>
                        <td>{{proveedor.nombre_proveedor}}</td>
                        <td>{{proveedor.direccion_proveedor}}</td>
                        <td>{{proveedor.comuna_proveedor}}</td>
                        <td>{{proveedor.correo_proveedor}}</td>
                        <td>{{proveedor.telefono_proveedor}}</td>
                        <td>
                            {% if proveedor.is_active == False %}
                                <span class="badge bg-danger">Inactivo</span>
                            {% else %}
                                <span class="badge bg-success">Activo</span>
                            {% endif %}
                        </td>
                        <td>
                            <a href="{% url 'detalleProveedores' proveedor.id_proveedor %}">
                                <button class="btn btn-primary">ver</button>
                            </a> 
                            <a href="{% url 'editarProveedor' proveedor.id_proveedor %}">
                                <button class="btn btn-warning">editar</button>
                            </a>
                            <button type="button" {% if proveedor.is_active == 0 %}class="btn btn-success"{% else %}class="btn btn-danger" {% endif %} data-bs-toggle="modal" data-bs-target="#exampleModal{{proveedor.id_proveedor}}">
                                {% if proveedor.is_active == 0 %}
                                Activar
                                {% else %}
                                Desactivar
                                {% endif %}
                            </button>
                            <!-- Modal -->
                            <div class="modal fade" id="exampleModal{{proveedor.id_proveedor}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            seguro que desea {% if proveedor.is_active == 0 %}
                                            Activar
                                            {% else %}
                                            Desactivar
                                            {% endif %} a {{proveedor}}
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                            <a href="{% url 'cambiarEstadoProveedor' proveedor.id_proveedor%}">
                                                <button type="button" {% if proveedor.is_active == 0 %}class="btn btn-success"{% else %}class="btn btn-danger" {% endif %}>
                                                    {% if proveedor.is_active == 0 %}
                                                    Activar
                                                    {% else %}
                                                    Desactivar
                                                    {% endif %}
                                                </button>
                                            </a>
                                      </div>
                                    </div>
                                </div>
                            </div>
                            <!-- Fin Modal -->  
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

libreria/inventario/templates/proveedores/registro.html
{% extends 'layout.html' %}
{% block contenido %}
<div class= "container p-3">
  <div class="card mb-3">
    <div class="card-header">
      <h3>
        {{titulo}}
      </h3>
    </div>
    <div class="card-body">
      <form action="{% url 'registroProveedores' %}" method = "POST">
          {% csrf_token %}
          <div class="mb-3">
              <label class="form-label">Nombre<span class="text-muted">(Campo Obligatorio)</span></label>
              <input type="text" class="form-control" id="nombreP" name="nombreP" required>
            </div>
          <div class="mb-3">
            <label class="form-label">Dirección<span class="text-muted">(Campo Obligatorio)</span></label>
            <input type="text" class="form-control" id="direccionP" name="direccionP" required>
          </div>
          <div class="mb-3">
            <label class="form-label">Comuna<span class="text-muted">(Campo Obligatorio)</span></label>
            <input type="text" class="form-control" id="comunaP" name="comunaP" required>
          </div>
          <div class="mb-3">
              <label class="form-label">Correo<span class="text-muted">(Campo Obligatorio)</span></label>
              <input type="email" class="form-control" id="correoP" name="correoP" required>
          </div>
          <div class="mb-3">
              <label class="form-label">Teléfono<span class="text-muted">(Campo Obligatorio)</span></label>
              <input type="text" class="form-control" id="telefonoP" name="telefonoP" required>
          </div>
          <br>
          <button type="submit" class="btn btn-primary">Registro</button>
        </form>

    </div>
  </div>
</div>
{% if toast %}
        <div class="toast-container text-bg-primary position-fixed bottom-0 start-0 p-3">
            {% if toast == "Error" %}
                <div id="liveToast" class="toast bg-danger text-light" role="alert" aria-live="assertive" aria-atomic="true">
            {% else %}
                <div id="liveToast" class="toast bg-success text-light" role="alert" aria-live="assertive" aria-atomic="true">
            {% endif %}
                <div class="toast-header">
                    <i class="fa-solid fa-circle-exclamation m-1"></i>
                    <strong class="me-auto">{{toast}}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
                <div class="toast-body">
                    {{mensaje}}
                </div>
            </div>
        </div>
        <script> 
            const toastLiveExample = document.getElementById('liveToast')
            const toast = new bootstrap.Toast(toastLiveExample)
            toast.show()
        </script>
        {% endif %}
{% endblock contenido %}